export const sidonCategories = [
  { carouselImage: "/home/worlds/sidon/mantenimiento-carousel.png", slug: "mantenimiento-seguridad", modules: [{ key: "mantiz", slug: "mantiz", icon: "/home/worlds/sidon/mantenimiento-modulos/Mantiz_Isotipo_Color.png" }, { key: "talos", slug: "talos", icon: "/home/worlds/sidon/mantenimiento-modulos/Talos_Isotipo_Color.png" }] },
  { carouselImage: "/home/worlds/sidon/auditorias-carousel.png", slug: "auditorias", modules: [{ key: "smartAudits", slug: "smart-audits", icon: "/home/worlds/sidon/auditorias-modulos/SmartAudits_Logotipo_Color.png" }, { key: "argos", slug: "argos", icon: "/home/worlds/sidon/auditorias-modulos/Argos_Isoptipo_Color.png" }, { key: "nodIa", slug: "nod-ia", icon: "/home/worlds/sidon/auditorias-modulos/Nodia_Isotipo_Color.png" }, { key: "rondines", slug: "rondines", icon: "/home/worlds/sidon/auditorias-modulos/Rondines_Isotipo_Color.png" }] },
  { carouselImage: "/home/worlds/sidon/personas-carousel.png", slug: "personas", modules: [{ key: "wellness", slug: "wellness", icon: "/home/worlds/sidon/personas-modulos/Wellnes_Isotipo_Color-39.png" }, { key: "byblos", slug: "byblos", icon: "/home/worlds/sidon/personas-modulos/Byblos_Isotipo_Color.png" }] },
  { carouselImage: "/home/worlds/sidon/acceso-carousel.png", slug: "acceso", modules: [{ key: "axessOne", slug: "axessone", icon: "/home/worlds/sidon/acceso-modulos/AxessONE_Isotipo_Color.png" }] },
  { carouselImage: "/home/worlds/sidon/monitoreo-carousel.png", slug: "monitoreo", modules: [{ key: "sense", slug: "sense", icon: "/home/worlds/sidon/monitoreo-modulos/Sense_Isotipo_Color.png" }, { key: "polar", slug: "polar", icon: "/home/worlds/sidon/monitoreo-modulos/Polar_Isotipo_Color.png" }, { key: "industrial", slug: "industrial", icon: "/home/worlds/sidon/monitoreo-modulos/Industrial_Isotipo_Color.png" }] },
] as const;

export type SidonCategorySlug = (typeof sidonCategories)[number]["slug"];
